### ISSUE TITLE
v3.1.0 breaks OpenSSH

### ISSUE THREAD

**Issue by leonklingele** [libressl/portable#590] opened 2020-05-10 10:08 UTC
When using LibreSSL v3.1.0 with OpenSSH (8.2p1), connections to OpenSSH servers can not be established — neither using keys nor passwords. It was working fine with LibreSSL v3.0.2 before. I haven't bisected the issue so far.

Using LibreSSL v3.1.0:

```sh
$ ssh server1
# showing last few lines only

debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ssh-rsa
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
debug1: Server host key: ssh-rsa SHA256:REDACTED_HOST_KEY
debug3: hostkeys_foreach: reading file "~/.ssh/known_hosts"
debug3: record_hostkey: found key type RSA in file ~/.ssh/known_hosts:59
debug3: load_hostkeys: loaded 1 keys from server1
debug3: hostkeys_foreach: reading file "~/.ssh/known_hosts"
debug3: record_hostkey: found key type RSA in file ~/.ssh/known_hosts:83
debug3: load_hostkeys: loaded 1 keys from server1_ip
debug1: Host 'server1' is known and matches the RSA host key.
debug1: Found key in ~/.ssh/known_hosts:59
debug3: send packet: type 21
debug2: set_newkeys: mode 1
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey in after 134217728 blocks

# stuck from now on, nothing happens
```

Using LibreSSL v3.0.2:

```sh
$ ssh server1
# same as above with v3.1.0, but it continues as follows:

debug1: Will attempt key: ~/.ssh/id_ed25519 ED25519 SHA256:REDACTED_HOST_KEY agent
debug1: Will attempt key: ~/.ssh/id_rsa RSA SHA256:REDACTED_HOST_KEY
debug2: pubkey_prepare: done
debug3: send packet: type 5
debug3: receive packet: type 7
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey
debug3: start over, passed a different list publickey
debug3: preferred publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey

# etc.
```

**Comment by botovq** [comment] 2020-05-10 10:24
@djmdjm @daztucker could you please take a look?

**Comment by daztucker** [comment] 2020-05-10 13:20
There's lots of variables here, but it's not anything obvious that I can see.

We regularly test OpenSSH head against LibreSSL head on OpenBSD and the only problem we've had was incorrectly enabling libressl's chacha20 on librressl versions prior to 3, but that was in code added after the OpenSSH 8.2p1 release.  I just tested OpenSSH 8.2p1 against LibreSSL 3.1.0 and 3.1.1 on Linux and it passed its regression tests.

It's possible there's an incompatibility between LibreSSL versions (we've had that once in the past with OpenSSL, where due to a bug in a specific version it would interop with itself but not anything else) but there's insufficient information in this report to determine in this case (eg, is the client, server or both using libressl 3.1.0?).   I interop tested against PuTTY, so again if it's that it's not anything obvious.

I'd suggest:
1) run libressl's self tests ("make check").
2) run openssh's regression tests ("make tests").  If you have PuTTY installed, you can add "REGRESS_INTEROP_PUTTY=yes" to enable those interop tests.
3) Try to figure out what it's doing when it's in the hung state.  A couple of ways are attach a debugger to the hung process and get a stack trace (eg "gdb /path/to/ssh [pidofprocess]", then "bt") and using a tool like strace or truss to get a system call trace ("strace -p "[pidofprocess]").  Compare results from both client and server.

If those don't pinpoint anything then we'll need a lot more information to try to narrow it down and/or reproduce it, including platform, compiler, configure flags and any other thing that might be specific to your installation.

**Comment by kinichiro** [comment] 2020-05-27 14:29
Hi, @leonklingele 
Is this still an issue for you ? Can you close this if it is solved ?

**Comment by leonklingele** [comment] 2020-05-27 20:51
Yes, unfortunately it still is — even with LibreSSL v3.1.2. I haven't tried to reproduce with OpenSSH 8.3 (which got released today) though.

I'll provide the requested information asap. Sorry for the delay!

**Comment by jkoderu-git** [comment] 2020-07-06 12:01
Openvpn is also broken.

Working logs, openvpn build with libressl 3.0.2
```
OpenVPN 2.4.9 x86_64-unknown-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Apr 30 2020
library versions: LibreSSL 3.0.2, LZO 2.10
Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
...
Control Channel: TLSv1.2, cipher TLSv1/SSLv3 DHE-RSA-AES256-GCM-SHA384, 4096 bit RSA
...
OPTIONS IMPORT: data channel crypto options modified
Data Channel: using negotiated cipher 'AES-256-GCM'
Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
...
```

Not working logs, openvpn build with libressl 3.1.3

```
openVPN 2.4.9 x86_64-unknown-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Jul  4 2020
library versions: LibreSSL 3.1.3, LZO 2.10
Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
TCP/UDP: Preserving recently used remote address: [AF_INET]{IP1}:1194
Socket Buffers: R=[212992->212992] S=[212992->212992]
UDP link local: (not bound)
UDP link remote: [AF_INET]{IP1}:1194
TLS: Initial packet from [AF_INET]{IP1}:1194, sid=38277fca 0cce7134
WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
TLS Error: TLS handshake failed
SIGUSR1[soft,tls-error] received, process restarting
Restart pause, 5 second(s)
TCP/UDP: Preserving recently used remote address: [AF_INET]{IP2}:1194
Socket Buffers: R=[212992->212992] S=[212992->212992]
UDP link local: (not bound)
UDP link remote: [AF_INET]{IP2}:1194
```

To reproduce connect to protonvpn with protonvpn-cli.

https://github.com/void-linux/void-packages/issues/23413

**Comment by kinichiro** [comment] 2020-07-07 09:13
I tested openssh-8.3p1 with libressl-3.1.3 on my Fedora 3.1 (x86_64).
Here is my procedure.
I had downloaded openssh-8.3p1.tar.gz and libressl-3.1.3.tar.gz from download site.

build libressl 3.1.3:
```
$ ./configure --prefix=<mydir>
$ make check
$ make install
```

build openssh 8.3p1:
```
$ export LD_LIBRARY_PATH=<mydir>/lib
$ ./configure --prefix=<mydir> --with-ssl-dir=<mydir>
$ make
$ make install
$ <mydir>/bin/ssh -V
OpenSSH_8.3p1, LibreSSL 3.1.3
```

Confirm which libcrypto.so is linked.
```
$ ldd <mydir>/bin/ssh
        linux-vdso.so.1 (0x00007ffc745f2000)
        libcrypto.so.46 => <mydir>/lib/libcrypto.so.46 (0x00007f77bbb8c000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f77bbb77000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f77bbb72000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f77bbb58000)
        libcrypt.so.2 => /lib64/libcrypt.so.2 (0x00007f77bbb1d000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f77bbb04000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f77bb939000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f77bb917000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f77bbe44000)
$
$ ls  <mydir>/lib/libcrypto.so.46
<mydir>/lib/libcrypto.so.46
```

Connection test:
```
$ <mydir>/bin/ssh -v localhost
OpenSSH_8.3p1, LibreSSL 3.1.3
debug1: Reading configuration data <mydir>/etc/ssh_config
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug1: Connecting to localhost [::1] port 22.
debug1: Connection established.

... (snip) ...

debug1: Local version string SSH-2.0-OpenSSH_8.3
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.1
debug1: match: OpenSSH_8.1 pat OpenSSH* compat 0x04000000

... (snip) ...

debug1: Authentication succeeded (password).
Authenticated to localhost ([::1]:22).
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
$
$
$ exit
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: client_input_channel_req: channel 0 rtype eow@openssh.com reply 0
debug1: channel 0: free: client-session, nchannels 1
Connection to localhost closed.
Transferred: sent 2376, received 2628 bytes, in 177.3 seconds
Bytes per second: sent 13.4, received 14.8
debug1: Exit status 0
$
```
I could successfully connected to localhost.
My localhost runs builtin sshd as "OpenSSH_8.1p1, OpenSSL 1.1.1g FIPS  21 Apr 2020".

I didn't see any troubles.

**Comment by 4a6f656c** [comment] 2020-07-31 16:48
@leonklingele - any update here?

Seems potentially related to https://github.com/libressl-portable/portable/issues/603.

**Comment by busterb** [comment] 2023-07-05 16:58
It's been a while, closing this.

**Closed by busterb** 2023-07-05 16:58 UTC
Labels: question
