### ISSUE TITLE
Error while building LibreSSL using Cygwin for Windows 10

### ISSUE THREAD

**Issue by Chaoticsys101** [libressl/portable#637] opened 2020-11-02 14:01 UTC
I have been trying to build LibreSSL 3.2.2 for Windows x64, I tried yesterday using MSYS2. Today I tried using Cygwin and I got the same error. I got the source file from the official releases website of LibreSSL.

The commands I entered:
$ CC=x86_64-w64-mingw32-gcc ./configure --host=x86_64-w64-mingw32 (this one worked fine) 
$ mingw32-make (this is where the error occurred) 

Here is a screenshot of the error and my mingw64 version.
![IMG_20201102_134631](https://user-images.githubusercontent.com/67800528/97876387-af71ff80-1d13-11eb-825d-e49d5dee7cc3.jpg)

**Comment by Chaoticsys101** [comment] 2020-11-02 22:02
Forgot to mention, the source I used is from https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/ and I'm just looking for a way to build it, I don't care how so if anyone could just provide me a way to do so I would be much appreciated.

**Comment by busterb** [comment] 2020-11-03 00:45
Howdy, I think this is a bug already be fixed in the master and OPENBSD_6_8 branches.

Are you able to test either of those out? Be sure you check the README if you do.

**Comment by Chaoticsys101** [comment] 2020-11-03 01:35
Hi, thanks for the reply. Could you send me a link of the file to download? Because I am not sure I know what you are referring to

**Comment by Chaoticsys101** [comment] 2020-11-03 01:36
Do you mean the master of libressl-portable/portable?

**Comment by busterb** [comment] 2020-11-03 02:24
Yes, this repository, though note that you do need to run autogen.sh successfully once first.

**Comment by Chaoticsys101** [comment] 2020-11-03 10:38
I will try and come back with the results

**Comment by ndavidpsi** [comment] 2020-11-03 12:15
weird... it says ./configure no such file or directory

**Comment by omasanori** [comment] 2020-11-03 12:17
@ndavidpsi have you run `./autogen.sh` before `./configure`?

**Comment by ndavidpsi** [comment] 2020-11-03 12:21
yes I have but I did it using cmd this time because I use git there. BTW what would you recommend using MSYS2 or Cygwin? I have both, just so that we are on the same page.

**Comment by ndavidpsi** [comment] 2020-11-03 12:23
on cygwin when I use ./autogen.sh it says invalid optionne 2: set: -
I'll try on MSYS2 which I'm more comfortable with

**Comment by Chaoticsys101** [comment] 2020-11-03 15:58
Update: it showed the same error... Do you have a Windows machine or VM? Could you try to build it yourself and see the result?

**Comment by Chaoticsys101** [comment] 2020-11-03 15:58
The only difference was that it took a lot longer to make

**Comment by omasanori** [comment] 2020-11-03 16:26
I am not sure who you refer to as you but anyway I am setting up MSYS2. Let's see...

**Comment by Chaoticsys101** [comment] 2020-11-03 16:47
I was asking if you had access to the Windows Operating System. Thanks, let me know what happens

**Comment by Chaoticsys101** [comment] 2020-11-03 16:52
Oh sorry, I basically meant anyone that's reading this. Thanks!

**Comment by Chaoticsys101** [comment] 2020-11-03 16:53
Oh it basically was meant to anyone who's reading this. Thanks! Let me know the results

**Comment by Chaoticsys101** [comment] 2020-11-03 18:25
@omasanori any luck?

**Comment by omasanori** [comment] 2020-11-03 18:57
Sure.

1. Install MSYS2 https://www.msys2.org/
2. Update packages by following instructions
3. Install developer tools by `pacman -S base-devel git mingw-w64-x86_64-toolchain` (not minimal but sufficient)
4. `git clone https://github.com/libressl-portable/portable.git libressl && cd libressl`
5. `./autogen.sh; ./configure`
6. `make`
7. `make check`

I hope it helps.

**Comment by Chaoticsys101** [comment] 2020-11-03 18:58
Thanks!! I will try it now.

**Comment by Chaoticsys101** [comment] 2020-11-03 20:42
@omasanori Update: alas after waiting a lot of time I got an error in step 6. I followed each step perfectly. 
![IMG_20201103_203623](https://user-images.githubusercontent.com/67800528/98038386-fdbaf780-1e14-11eb-9135-fcd1e731f2e0.jpg)

**Comment by omasanori** [comment] 2020-11-04 00:31
@Chaoticsys101 Confirmed. This seems https://github.com/msys2/MINGW-packages/issues/5868.
I am trying `CFLAGS=-fstack-protector LDFLAGS=-lssp ./configure` now.

**Comment by Chaoticsys101** [comment] 2020-11-04 00:34
You're right, it does seem like it. Alright

**Comment by omasanori** [comment] 2020-11-04 02:37
OK, I ran `make check` without failure. Two approaches by the build scripts on MinGW-w64 are available AFAIK:
- Making sure that libssp is linked: carrying `libssp-0.dll` around could be a source of headache if it was linked dynamically.
- Weakening `_FORTIFY_SOURCE`: sounds scary as we are talking about a crypto library, but...

**Comment by busterb** [comment] 2020-11-04 07:27
Sounds like something changed in newer mingw, since this is still passing with the version running against the Travis CI tests. This project was already making the libssp linking optional, enabled via the --enable-windows-ssp option, so it may be necessary to modify the tests in m4/check-hardening-options.m4

./configure --host=x86_64-w64-mingw32 --enable-windows-ssp

Note that the mingw ssp problem is different than the original problem reported here, which was due to an issue linking libcompat when certain compatibility functions were required. That appears to be resolved, thanks for double-checking.

**Comment by omasanori** [comment] 2020-11-04 07:33
> Note that the mingw ssp problem is different than the original problem reported here, which was due to an issue linking libcompat when certain compatibility functions were required. That appears to be resolved, thanks for double-checking.

Exactly, I am sorry if someone is confused by my comments.

**Comment by Chaoticsys101** [comment] 2020-11-04 09:51
So what would be the best procedure to build it for windows? I don't want to make it less secure. Is there a way to build it in Linux using its own tools for Windows? I tried on Linux building the tar gz from https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/ and it went well without any errors.

**Comment by Chaoticsys101** [comment] 2020-11-04 13:50
@busterb update: it worked great with --enable-windows-ssp! But what does that option actually do and does it affect the security of LibreSSL in any way?

**Comment by Chaoticsys101** [comment] 2020-11-04 17:31
Actually I got an error while doing the make install. It said it couldn't locate something about the man files

**Comment by Chaoticsys101** [comment] 2020-11-04 19:04
Here is the make install error
![Capturar](https://user-images.githubusercontent.com/67800528/98157007-95c9e700-1ed0-11eb-953f-884ae38ba515.PNG)

**Comment by busterb** [comment] 2023-07-05 16:02
We had some issues with manpages using invalid characters on Windows filesystems previously, but these should be fixed now as well.

**Closed by busterb** 2023-07-05 16:02 UTC
