### ISSUE TITLE
3.8.2 build failure on old Mac

### ISSUE THREAD

**Issue by robmaz** [libressl/portable#952] opened 2023-11-28 10:57 UTC
3.8.2 fails to build with default config on a MacPro (Early 2009) with MacOS 10.11.6 and compiler version

  $ as --version
  Apple LLVM version 8.0.0 (clang-800.0.42.1)
  Target: x86_64-apple-darwin15.6.0
  Thread model: posix
  InstalledDir: /Library/Developer/CommandLineTools/usr/bin

  $ ./configure && make
  ...
  Making all in crypto
  echo "generating crypto_portable.sym ..."
  generating crypto_portable.sym ...
  cp ../crypto/crypto.sym crypto_portable.sym
  chmod u+w crypto_portable.sym
  /Library/Developer/CommandLineTools/usr/bin/make  all-am
    CPPAS    aes/libcrypto_la-aes-macosx-x86_64.lo
    CPPAS    aes/libcrypto_la-bsaes-macosx-x86_64.lo
    CPPAS    aes/libcrypto_la-vpaes-macosx-x86_64.lo
    CPPAS    aes/libcrypto_la-aesni-macosx-x86_64.lo
  aes/aesni-macosx-x86_64.S:890:2: error: invalid instruction mnemonic 'endbr64'
   endbr64
   ^~~~~~~
  make[2]: *** [aes/libcrypto_la-aesni-macosx-x86_64.lo] Error 1
  make[1]: *** [all] Error 2
  make: *** [all-recursive] Error 1

Looks like it is trying to compile an assembler file it shouldn't for this system? 

Libressl versions up to 3.7.3 build fine, so this is a regression.

**Comment by busterb** [comment] 2023-11-29 18:52
Hi, this was reported in some other tickets as well; we'll have it addressed in the next release.

**Comment by busterb** [comment] 2023-11-29 18:53
Duplicate of #933

**Closed by busterb** 2023-11-29 18:53 UTC
