### ISSUE TITLE
There may be an issue with incorrect validation of expiry dates

### ISSUE THREAD

**Issue by ydgydg** [libressl/portable#831] opened 2023-03-29 08:13 UTC
When I used Libressl for certificate validation, I discovered that Libressl had incorrectly passed an expired digital certificate. Is this a bug here？Or do I have some misunderstandings on openssl in its parsing or verification procedure?
The command I used is:
`openssl verify -CAfile root.pem leaf.pem `
The validation results：
`ok`
Perhaps there was a mistake in my operation?

**Comment by ydgydg** [comment] 2023-03-30 14:46
Here is the certificate file I used, and the version number is 3.4.1
[leaf.txt](https://github.com/libressl/portable/files/11112848/leaf.txt)
[root.txt](https://github.com/libressl/portable/files/11112849/root.txt)

**Comment by job** [comment] 2023-04-23 16:59
@ydgydg can you try with a more recent version of LibreSSL? I cannot reproduce:

```
$ openssl verify -CAfile root.pem leaf.pem
C = CN, ST = TJ5, L = TJ, O = TJU, OU = beiyangyuan, CN = LQL, emailAddress = ljfpower@163.com
error 20 at 0 depth lookup:unable to get local issuer certificate
leaf.pem: verification failed: 20 (unable to get local issuer certificate)

$ openssl version
LibreSSL 3.7.2
```

**Comment by llmlla** [comment] 2023-04-24 01:43
OK, I'll try it as you suggest

**Comment by joshuasing** [comment] 2024-03-25 12:31
Closing due to there being no further response. Please reopen if this is still an issue.

**Closed by joshuasing** 2024-03-25 12:31 UTC
