### ISSUE TITLE
Gentoo QA Notice for libressl-3.7.1

### ISSUE THREAD

**Issue by orbea** [libressl/portable#825] opened 2023-03-16 19:05 UTC
On Gentoo when building `libressl-3.7.1` with `gcc-12.2.1_p20230121-r1` this warning is emitted .
>  * QA Notice: Package triggers severe warnings which indicate that it may exhibit random runtime failures.
>  * /var/tmp/portage/dev-libs/libressl-3.7.1/work/libressl-3.7.1/ssl/s3_cbc.c:529:9: warning: 'memcpy' forming offset 128 is out of the bounds [0, 128] of object 'hmac_pad' with type 'unsigned char[128]' [-Warray-bounds]

And the whole warning can be seen:
```
/var/tmp/portage/dev-libs/libressl-3.7.1/work/libressl-3.7.1/ssl/s3_cbc.c: In function 'ssl3_cbc_digest_record':
/var/tmp/portage/dev-libs/libressl-3.7.1/work/libressl-3.7.1/ssl/s3_cbc.c:529:9: warning: 'memcpy' forming offset 128 is out of the bounds [0, 128] of object 'hmac_pad' with type 'unsigned char[128]' [-Warray-bounds]
  529 |         memcpy(hmac_pad, mac_secret, mac_secret_length);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/dev-libs/libressl-3.7.1/work/libressl-3.7.1/ssl/s3_cbc.c:403:23: note: 'hmac_pad' declared here
  403 |         unsigned char hmac_pad[MAX_HASH_BLOCK_SIZE];
      |                       ^~~~~~~~
```

**Comment by botovq** [comment] 2023-03-16 19:19
I've seen this warning and it didn't make any sense to me:

```
528         OPENSSL_assert(mac_secret_length <= sizeof(hmac_pad));
529         memcpy(hmac_pad, mac_secret, mac_secret_length);
```

So the line before asserts that there is enough room to copy
mac_secret_length bytes into hmac_pad.

**Comment by botovq** [comment] 2023-04-28 21:34
The issue is that gcc can't see that OPENSSL_assert() will not return
because it is in a different library. This patch avoids the warning:

https://github.com/libressl/portable/pull/850/commits/bc0a7021eda496c3865a0b1aa6ad1100f3a99913

**Comment by orbea** [comment] 2023-04-30 02:55
Thanks that patch silences the compiler warning and QA notice, wouldn't it be better to be explicit with the noreturn attribute to make gcc (And Gentoo's QA) happy? Or is there some reason to not merge it? It might seem silly, but is it actually problematic?

**Comment by botovq** [comment] 2023-04-30 04:07
I only made the PR as a patch for portable to ensure that all platforms
in CI are happy with it. Once I knew that was the case, I merged it
directly into our main source tree:

https://github.com/openbsd/src/commit/a988a9f4686156ada7b5b06ba452644ca92a318c

**Comment by orbea** [comment] 2023-04-30 13:26
Oh, thanks for explaining, I didn't catch that earlier. I suppose this issue can be closed when the new release is out?

**Comment by orbea** [comment] 2023-04-30 16:39
Actually there is an issue with this approach, libvncserver-0.9.14 now fails.
```
samu: job failed: /usr/lib/ccache/bin/x86_64-gentoo-linux-musl-gcc -DLIBVNCSERVER_HAVE_LIBJPEG -DLIBVNCSERVER_HAVE_LIBPNG -DLIBVNCSERVER_HAVE_LIBZ -DLIBVNCSERVER_WITH_WEBSOCKETS -Dvncserver_EXPORTS -I/var/tmp/portage/net-libs/libvncserver-0.9.14/work/libvncserver-LibVNCServer-0.9.14 -I/var/tmp/portage/net-libs/libvncserver-0.9.14/work/libvncserver-LibVNCServer-0.9.14_build -I/var/tmp/portage/net-libs/libvncserver-0.9.14/work/libvncserver-LibVNCServer-0.9.14/libvncserver -I/var/tmp/portage/net-libs/libvncserver-0.9.14/work/libvncserver-LibVNCServer-0.9.14/common  -O2 -pipe -Werror=implicit-function-declaration -Werror=implicit-int -fPIC -std=gnu90 -MD -MT CMakeFiles/vncserver.dir/libvncserver/rfbssl_openssl.c.o -MF CMakeFiles/vncserver.dir/libvncserver/rfbssl_openssl.c.o.d -o CMakeFiles/vncserver.dir/libvncserver/rfbssl_openssl.c.o -c /var/tmp/portage/net-libs/libvncserver-0.9.14/work/libvncserver-LibVNCServer-0.9.14/libvncserver/rfbssl_openssl.c
In file included from /usr/include/openssl/bio.h:69,
                 from /usr/include/openssl/evp.h:67,
                 from /usr/include/openssl/hmac.h:67,
                 from /usr/include/openssl/ssl.h:150,
                 from /var/tmp/portage/net-libs/libvncserver-0.9.14/work/libvncserver-LibVNCServer-0.9.14/libvncserver/rfbssl_openssl.c:25:
/usr/include/openssl/crypto.h:491:7: error: expected ';' before 'void'
  491 | __dead void OpenSSLDie(const char *file, int line, const char *assertion);
      |       ^~~~~
      |       ;
samu: subcommand failed
 * ERROR: net-libs/libvncserver-0.9.14::gentoo failed (compile phase)
```

**Comment by botovq** [comment] 2023-04-30 16:44
Does it compile if you add '#include <sys/types.h>' at the top of crypto.h?

**Comment by botovq** [comment] 2023-04-30 17:06
Judging from the linux systems I currently have access to that won't
work. We could add

#ifndef __dead
#define __dead
#endif

to crypto.h, but this goes a step too far in my opinion.

We have identified this QA Notice as a non-issue in more than one way.
I'd be inclined to ignore it.

**Comment by orbea** [comment] 2023-04-30 17:19
Yea, I can confirm that didn't work while your second suggestion does.
```
diff --git a/include/openssl/crypto.h b/include/openssl/crypto.h
index 066f624..98a2b06 100644
--- a/include/openssl/crypto.h
+++ b/include/openssl/crypto.h
@@ -132,6 +132,10 @@
 extern "C" {
 #endif
 
+#ifndef __dead
+#define __dead
+#endif
+
 /* Backward compatibility to SSLeay */
 /* This is more to be used to check the correct DLL is being used
  * in the MS world. */
@@ -488,7 +492,7 @@ typedef int *CRYPTO_MEM_LEAK_CB(unsigned long, const char *, int, int, void *);
 int CRYPTO_mem_leaks_cb(CRYPTO_MEM_LEAK_CB *cb);
 
 /* die if we have to */
-void OpenSSLDie(const char *file, int line, const char *assertion);
+__dead void OpenSSLDie(const char *file, int line, const char *assertion);
 #define OPENSSL_assert(e)       (void)((e) ? 0 : (OpenSSLDie(__FILE__, __LINE__, #e),1))
 
 uint64_t OPENSSL_cpu_caps(void);
```
However I share your sentiment that it seems a bit silly, but I am not sure if its bad enough to not silence warnings even if they are false positives? I'll leave it the best judgement of the libressl developers, feel free to close this issue if you feel that is best.

**Comment by botovq** [comment] 2023-07-07 15:21
Fixed by https://github.com/libressl/openbsd/commit/27333fb436b5929303f0e12e36f3b00af78264a3

**Closed by botovq** 2023-07-07 15:21 UTC
